SILKIT-1477 SystemController Utility: Use SignalHandler, better report state
vectorgrp/sil-kit pull request #33
Opened 2024-04-25 17:48 UTC by AndreasRentschler

## Subject

Improvements of SystemController utility

## Description

[SILKIT-1477](https://jira.vg.vector.int/browse/SILKIT-1477)
System controller blocks new participants after required participants have terminated

- SystemController did not consistently report about the system's shutdown/error state.
- Reconnecting a participant after the system went into Shutdown state made the SystemController appear to hang.
- Changed to SignalHandler approach to allow for implicit exit after shutdown (`std::cin.ignore()` cannot be canceled).
  SIgnalHandler had to be turned into a reusable module, previously owned by Registry utility.
- Bugfix: Warning on valid transition from Aborting to Shutdown
- RequestReply was ignored when barrier has not yet been passed. Now, a warning is emitted and the new RequestReply is executed.

## Instructions for review / testing

- SignalHandler, refactored for public use
- Changes in SystemStateTracker.cpp and LifecycleStates.cpp

## Developer checklist (address before review)

- [ ] Changelog.md updated
- [ ] Prepared update for depending repositories
- [ ] Documentation updated (public API changes only)
- [ ] API docstrings updated (public API changes only)
- [ ] Rebase &rarr; commit history clean
- [ ] Squash and merge &rarr; proper PR title

2024-04-26 10:40 UTC, MariusBgm requested changes
Only looked at the SignalHandler.cpp: we should initialize the stack variables

2024-04-26 10:40 UTC, MariusBgm commented on SilKit/source/util/SignalHandler.cpp
> +    struct sigaction oldAction;
```suggestion
    struct sigaction oldAction{};
```
better default initialize variables on stack

2024-04-26 10:40 UTC, MariusBgm commented on SilKit/source/util/SignalHandler.cpp
> +    struct sigaction newAction;
```suggestion
    struct sigaction newAction{};
```
definitely initialize this here, as there might be garbage on the stack

2024-04-26 10:40 UTC, MariusBgm commented on SilKit/source/util/SignalHandler.cpp
> +        // A non-job-control shell wants us to ignore this kind of signal
should we bail out here? if the sa_handler is set to SIG_IGN, our parent process already set it?

```suggestion
        // A non-job-control shell wants us to ignore this kind of signal
        return;
```

2024-04-26 12:53 UTC, KonradBkd requested changes
The two critical changes should be reverted, otherwise ok👍

2024-04-26 12:53 UTC, KonradBkd commented on SilKit/source/core/requests/procs/ParticipantReplies.cpp
> -            return;
Rückbau

2024-04-26 12:53 UTC, KonradBkd commented on SilKit/source/services/orchestration/LifecycleStates.cpp
> -                _lifecycleManager->GetService()->SetFinalStatePromise();
Rückbau

2024-04-26 18:18 UTC, AndreasRentschler commented
Thanks for your reviews, all suggestions were implemented.

2024-04-29 07:10 UTC, KonradBkd approved these changes
LGTM

2024-05-06 13:50 UTC, MariusBgm approved these changes

2024-05-07 13:52 UTC, merged